### PR TITLE
Getting the cmake structure down, gitversion was a little bit of a pain

### PR DESCRIPTION
**Pull request by scottcoughlin2014**
Allowing compilation of package using cmake.

### CODE REVIEW

**Comment by scottcoughlin2014** [comment]
Only issue is that I had to change the way gitversion was printed in
```gbmcmc/src/GalacticBinaryIO.c```

**Comment by tlittenberg** [comment]
What should I use for ${CONDA_PREFIX}?

**Comment by scottcoughlin2014** [comment]
I will get this done tyson

**Comment by scottcoughlin2014** [comment]
Ok I think that the executables from `gbmcmc` should be installed and built now!

**Comment by tlittenberg** [comment]
Thanks a ton Scotty.

**Pull request merged**
